package com.deepmost.rabbitav.core.alerts

/** Alert families (Section 5.5). */
enum class AlertKind {
    FCW,
    WRONG_SIDE,
    VRU,
    HEADWAY,
    HAZARD_MAPPED,
    HAZARD_VISUAL,
}

/** Escalation levels; ordering matters (ordinal comparisons). */
enum class AlertLevel {
    NONE,
    ADVISORY,
    CAUTION,
    WARNING,
    CRITICAL,
}

/** Tone assets (generated by scripts/generate_tones.py into assets/audio/). */
enum class Tone(val assetFile: String, val loops: Boolean = false) {
    FCW_CAUTION("audio/fcw_caution.wav"),
    FCW_CRITICAL("audio/fcw_critical.wav", loops = true),
    HEADWAY_ADVISORY("audio/headway_advisory.wav"),
    HEADWAY_WARNING("audio/headway_warning.wav"),
    VRU("audio/vru.wav"),
    HAZARD_MAPPED("audio/hazard_mapped.wav"),
    HAZARD_VISUAL("audio/hazard_visual.wav"),
    WRONG_SIDE("audio/wrong_side.wav", loops = true),
    ADAS_SUSPENDED("audio/adas_suspended.wav"),
    ADAS_RESUMED("audio/adas_resumed.wav"),
    REPORT_ACK("audio/report_ack.wav"),
}

/**
 * One live alert produced by an engine for the current tick. Engines emit the
 * complete current set every tick; the arbiter diffs against the previous
 * tick for audio onset/clear behavior.
 */
data class ActiveAlert(
    val kind: AlertKind,
    val level: AlertLevel,
    val tone: Tone,
    /** Track that caused it; -1 for site-based (mapped hazard) alerts. */
    val trackId: Int = -1,
    /** Distance to the subject (m), NaN when meaningless. */
    val distanceM: Float = Float.NaN,
    /** TTC or headway seconds driving the alert, NaN when meaningless. */
    val secondsToEvent: Float = Float.NaN,
    /** Spoken TTS callout (already localized), empty = tone only. */
    val speech: String = "",
    /** HUD text key resolved by the UI layer. */
    val hudTextKey: String = "",
) {
    /** Global audio/visual priority (Section 5.5 ordering). */
    val priority: Int
        get() = when {
            kind == AlertKind.FCW && level == AlertLevel.CRITICAL -> 100
            kind == AlertKind.WRONG_SIDE -> 90
            kind == AlertKind.VRU -> 80
            kind == AlertKind.FCW -> 70
            kind == AlertKind.HEADWAY && level >= AlertLevel.WARNING -> 60
            kind == AlertKind.HAZARD_MAPPED -> 50
            kind == AlertKind.HAZARD_VISUAL -> 45
            else -> 40 // headway advisory
        }

    /** Identity for onset/clear diffing (level escalation = new onset). */
    val identity: Long
        get() = (kind.ordinal.toLong() shl 40) or
            (level.ordinal.toLong() shl 32) or
            (trackId.toLong() and 0xFFFFFFFFL)
}
