package com.deepmost.rabbitav

import com.deepmost.rabbitav.core.imu.BandPass
import com.deepmost.rabbitav.core.imu.HazardCandidate
import com.deepmost.rabbitav.core.imu.HazardType
import com.deepmost.rabbitav.core.imu.JoltDetector
import kotlin.math.PI
import kotlin.math.sin
import kotlin.math.sqrt
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * M3 gate: bundled sensor CSVs replayed through the full band-pass -> MAD
 * trigger -> feature -> classifier chain produce the correct classifications.
 * Fixtures generated by scripts/generate_imu_fixtures.py (raw az incl. gravity).
 */
class JoltEngineTest {

    private fun replay(resource: String, hasGyro: Boolean = false): List<HazardCandidate> {
        val candidates = mutableListOf<HazardCandidate>()
        val detector = JoltDetector(fsHz = 200f, hasGyro = hasGyro) { candidates.add(it) }
        detector.egoSpeedMps = { 30f / 3.6f } // 30 km/h, above the 8 km/h gate

        val stream = requireNotNull(javaClass.getResourceAsStream("/imu/$resource")) {
            "missing fixture $resource"
        }
        stream.bufferedReader().useLines { lines ->
            for (line in lines.drop(1)) {
                val parts = line.split(',')
                if (parts.size < 2) continue
                val tNs = (parts[0].toDouble() * 1e9).toLong()
                val az = parts[1].toFloat()
                // vertical deviation = raw vertical minus gravity (the aligner's job)
                detector.process(az - 9.81f, Float.NaN, tNs)
            }
        }
        return candidates
    }

    @Test
    fun speedBreakerClassified() {
        val candidates = replay("speed_breaker.csv")
        assertTrue("expected a candidate", candidates.isNotEmpty())
        assertEquals(HazardType.SPEED_BREAKER, candidates.first().type)
        assertTrue("confidence ${candidates.first().imuConfidence}", candidates.first().imuConfidence >= 0.6f)
    }

    @Test
    fun potholeClassified() {
        val candidates = replay("pothole.csv")
        assertTrue(candidates.isNotEmpty())
        assertEquals(HazardType.POTHOLE, candidates.first().type)
    }

    @Test
    fun roughPatchClassified() {
        val types = replay("rough_patch.csv").map { it.type }
        assertTrue("expected ROUGH_PATCH in $types", HazardType.ROUGH_PATCH in types)
        assertTrue("no breaker/pothole misfire in $types",
            types.none { it == HazardType.SPEED_BREAKER || it == HazardType.POTHOLE })
    }

    @Test
    fun smoothRoadStaysQuiet() {
        assertTrue(replay("smooth.csv").isEmpty())
    }

    @Test
    fun noGyroCapsConfidence() {
        val candidates = replay("speed_breaker.csv", hasGyro = false)
        assertTrue(candidates.first().imuConfidence <= JoltDetector.NO_GYRO_CONF_CAP + 1e-3f)
    }

    @Test
    fun speedGateSuppressesTriggers() {
        val candidates = mutableListOf<HazardCandidate>()
        val detector = JoltDetector(200f, false) { candidates.add(it) }
        detector.egoSpeedMps = { 1f } // below 8 km/h
        // hammer it with a huge synthetic jolt
        var t = 0L
        for (i in 0 until 2000) {
            val v = if (i in 900..920) 8f else 0f
            detector.process(v, Float.NaN, t)
            t += 5_000_000L
        }
        assertTrue(candidates.isEmpty())
    }
}

/** Band-pass magnitude response (0.8-30 Hz at fs 200). */
class ButterworthTest {

    private fun gainAt(freq: Float, fs: Float = 200f): Float {
        val bp = BandPass(fs)
        val n = (fs * 8).toInt()
        var sumSq = 0.0
        var count = 0
        for (i in 0 until n) {
            val x = sin(2.0 * PI * freq * i / fs).toFloat()
            val y = bp.process(x)
            if (i > n / 2) { // settled
                sumSq += (y * y).toDouble()
                count++
            }
        }
        val rms = sqrt(sumSq / count)
        return (rms * sqrt(2.0)).toFloat() // sine amplitude from RMS
    }

    @Test
    fun passbandIsFlat() {
        assertEquals(1f, gainAt(5f), 0.15f)
        assertEquals(1f, gainAt(12f), 0.15f)
    }

    @Test
    fun dcAndDriftRejected() {
        assertTrue(gainAt(0.1f) < 0.15f)
    }

    @Test
    fun highFrequencyBuzzRejected() {
        assertTrue(gainAt(80f) < 0.30f)
    }
}
