package com.deepmost.rabbitav

import android.Manifest
import android.os.Build
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.rule.GrantPermissionRule
import com.deepmost.rabbitav.core.alerts.AlertKind
import com.deepmost.rabbitav.core.alerts.AlertLevel
import com.deepmost.rabbitav.core.data.repo.CalibrationRepository
import com.deepmost.rabbitav.core.geometry.VehiclePreset
import com.deepmost.rabbitav.service.DriveForegroundService
import com.deepmost.rabbitav.service.DriveMode
import com.deepmost.rabbitav.service.DrivePipeline
import dagger.hilt.android.testing.HiltAndroidRule
import dagger.hilt.android.testing.HiltAndroidTest
import java.io.File
import javax.inject.Inject
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * The M2 acceptance gate, on-device (Section 7): a replay video of an
 * approaching vehicle, with synthetic ego speed set, fires FCW CAUTION and
 * then CRITICAL deterministically.
 *
 * The video (androidTest assets/approach.mp4, generated by
 * scripts/generate_test_video.py) scripts a bus approach from 10 m to 1.5 m at
 * 1.7 m/s closing with IPM-consistent geometry for the calibration profile the
 * test installs (sedan, pitch 1.7 deg). The clip loops; the alert sequence
 * repeats every ~7 s pass.
 */
@HiltAndroidTest
@RunWith(AndroidJUnit4::class)
class ReplayGateTest {

    @get:Rule(order = 0)
    val hiltRule = HiltAndroidRule(this)

    @get:Rule(order = 1)
    val permissions: GrantPermissionRule = if (Build.VERSION.SDK_INT >= 33) {
        GrantPermissionRule.grant(
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.POST_NOTIFICATIONS,
        )
    } else {
        GrantPermissionRule.grant(
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.ACCESS_COARSE_LOCATION,
        )
    }

    @Inject lateinit var pipeline: DrivePipeline
    @Inject lateinit var calibrationRepository: CalibrationRepository

    @Before
    fun setUp() {
        hiltRule.inject()
    }

    @Test
    fun approachVideoFiresCautionThenCritical() = runBlocking {
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val appContext = instrumentation.targetContext

        // Stage the clip from test assets into the app's replay dir. Unique
        // name: an adb-pushed twin would be shell-owned and unwritable here.
        val testDir = File(appContext.filesDir, "test-videos").apply { mkdirs() }
        val video = File(testDir, "approach-gate.mp4")
        instrumentation.context.assets.open("approach.mp4").use { input ->
            video.outputStream().use { input.copyTo(it) }
        }

        // Calibration matching the video's baked geometry (Section 5.9 profile).
        calibrationRepository.saveProfile(
            name = "replay-gate",
            preset = VehiclePreset.SEDAN,
            cameraHeightM = 1.30f,
            pitchRad = Math.toRadians(1.7).toFloat(),
            makeActive = true,
        )

        DriveForegroundService.start(appContext, DriveMode.REPLAY, video.absolutePath)
        try {
            withTimeout(60_000) {
                while (!pipeline.hud.value.running) delay(200)
            }
            pipeline.setSyntheticSpeedKmh(50f) // above every speed gate

            var sawCaution = false
            var sawCritical = false
            withTimeout(120_000) {
                while (!sawCaution || !sawCritical) {
                    val top = pipeline.hud.value.topAlert
                    if (top != null && top.kind == AlertKind.FCW) {
                        if (top.level == AlertLevel.CAUTION) sawCaution = true
                        if (top.level == AlertLevel.CRITICAL) {
                            // escalation implies the caution band was crossed
                            sawCaution = true
                            sawCritical = true
                        }
                    }
                    delay(40)
                }
            }
            assertTrue("FCW CAUTION fired", sawCaution)
            assertTrue("FCW CRITICAL fired", sawCritical)
        } finally {
            DriveForegroundService.stop(appContext)
            withTimeout(20_000) {
                while (pipeline.isRunning) delay(250)
            }
        }
    }
}
